# cargo-release test configuration
# This is a safer configuration for testing release automation

# Global settings
shared-version = true
allow-branch = ["feat/release-automation-testing"]

# Pre-release checks
pre-release-commit-message = "chore: prepare test release {{version}}"

# Git settings
tag-message = "chore: test release {{version}}"
tag-name = "test-v{{version}}"
push-remote = "origin"

# Publishing settings (disabled for testing)
publish = false
push = true
tag = true

# Pre-release hooks
pre-release-hook = [
    "cargo test --workspace --all-features",
    "cargo check --workspace --all-features",
    "cargo fmt --check",
    "cargo clippy --workspace --all-features -- -D warnings"
]