# cargo-release configuration
# https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

# Global settings
shared-version = true

# Pre-release checks
pre-release-commit-message = "chore: release {{version}}"

# Git settings
tag-message = "chore: release {{version}}"
tag-name = "v{{version}}"
push-remote = "origin"

# Publishing settings
publish = true
push = true
tag = true

# Pre-release hooks
pre-release-hook = [
    "cargo test --all-features",
    "cargo check --all-features"
]