# cargo-release production configuration
# https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

# Global settings
shared-version = true

# Pre-release checks
pre-release-commit-message = "chore: release v{{version}}"

# Git settings
tag-message = "Release v{{version}}"
tag-name = "v{{version}}"
push-remote = "origin"

# Publishing settings
publish = true
push = true
tag = true

# Pre-release hooks (disabled due to workspace issues)
# pre-release-hook = [
#     "cargo test --workspace --all-features",
#     "cargo check --workspace --all-features",
#     "cargo fmt --check",
#     "cargo clippy --workspace --all-features -- -D warnings"
# ]