# cargo-release test configuration
# This is a safer configuration for testing release automation

# Global settings
shared-version = true
allow-branch = ["feat/release-automation-testing"]

# Pre-release checks
pre-release-commit-message = "chore: prepare test release {{version}}"

# Git settings
tag-message = "chore: test release {{version}}"
tag-name = "test-v{{version}}"
push-remote = "origin"

# Publishing settings (disabled for testing)
publish = false
push = true
tag = true

# Pre-release hooks (simplified for testing)
pre-release-hook = [
    "cargo check --workspace --all-features"
]