# cargo-release configuration
# https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

# Global settings
shared-version = true

# Pre-release checks
pre-release-commit-message = "chore: release"

# Git settings
tag-message = "chore: release"
tag-name = "v{{version}}"
push-remote = "origin"

# Publishing settings
publish = true
push = true
tag = true

# Pre-release hooks (disabled for now)
# pre-release-hook = [
#     "cargo test --workspace --all-features",
#     "cargo check --workspace --all-features"
# ]