name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        name: hsipc ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        body: |
          Release ${{ steps.get_version.outputs.VERSION }}
          
          ## Changes
          
          See [CHANGELOG.md](https://github.com/loyalpartner/hsipc/blob/master/CHANGELOG.md) for detailed changes.
          
          ## Installation
          
          ```bash
          cargo add hsipc
          ```
          
          ## Documentation
          
          - [API Documentation](https://docs.rs/hsipc)
          - [GitHub Repository](https://github.com/loyalpartner/hsipc)

  publish-crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: create-release
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
    
    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Verify project builds
      run: cargo build --release --all-features
    
    - name: Run tests
      run: cargo test --release --all-features
    
    - name: Publish hsipc-macros
      run: |
        cd hsipc-macros
        cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
        # Wait for crates.io to process the package
        sleep 30
    
    - name: Publish hsipc
      run: |
        cd hsipc  
        cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: publish-crates
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
    
    - name: Generate documentation
      run: cargo doc --all-features --no-deps
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
        destination_dir: docs